#!/bin/bash

# Skip pre-push checks if SKIP_PREPUSH_CHECKS is set.
if [ "$SKIP_PREPUSH_CHECKS" = true ] || [ "$SKIP_PREPUSH_CHECKS" = 1 ] ; then
  echo "=== Skipping pre-push typescript and linter checks ==="
  exit 0
fi

# Run typecheck and linter before push.
ROOT_DIR=$(git rev-parse --show-toplevel)
cd "$ROOT_DIR"/frontend

echo "==== Running typecheck for frontend ===="

yarn typecheck > /dev/null
if [ $? -ne 0 ]; then
  echo "⛔ Typecheck failed! To see the errors, run \`yarn typecheck\` in the frontend directory."
  echo "   You can skip pre-push checks by setting \$SKIP_PREPUSH_CHECKS=true"
  exit 1
fi
echo "✅ Typecheck successful!"
