const { arrayOf, getId } = require('@semapps/ldp');

/**
 * Service to clean up Pods data
 */
module.exports = {
  name: 'cleanup',
  actions: {
    async deleteUpdateActivities(ctx) {
      const { username } = ctx.params;
      const accounts = await ctx.call('auth.account.find', { query: username === '*' ? undefined : { username } });

      for (const { username: dataset, webId } of accounts) {
        ctx.meta.dataset = dataset;
        ctx.meta.webId = webId;

        this.logger.info(`Looking for Update activities generated by ${webId}...`);

        const container = await ctx.call('activitypub.activity.list', {
          filters: {
            a: 'https://www.w3.org/ns/activitystreams#Update'
          }
        });

        for (const updateActivity of arrayOf(container['ldp:contains'])) {
          this.logger.info(`Deleting Update activity ${getId(updateActivity)}...`);
          await ctx.call('activitypub.activity.delete', {
            resourceUri: getId(updateActivity)
          });
        }
      }
    }
  }
};
