FROM node:20-alpine

RUN node -v
RUN npm -v

RUN apk add --update --no-cache autoconf bash libtool automake python3 py3-pip alpine-sdk openssh-keygen yarn nano

RUN yarn global add serve

ADD frontend /app/frontend

WORKDIR /app/frontend

RUN yarn install

RUN yarn run build

EXPOSE 5000

# This variable is only used on runtime
ENV CONFIG_URL http://localhost:3000/.well-known/config.js

CMD docker-entrypoint.sh
