services:
  traefik:
    image: traefik:v3.3
    container_name: traefik
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./docker/traefik/traefik.yml:/etc/traefik/traefik.yml:ro
      - ./docker/traefik/dynamic:/etc/traefik/dynamic:ro
      - letsencrypt:/letsencrypt
    environment:
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}

  domain-guard:
    build:
      context: ./docker/domain-guard
      dockerfile: Dockerfile
    container_name: domain-guard
    restart: unless-stopped
    expose:
      - '3000'
    labels:
      - 'traefik.enable=false'

  fuseki:
    image: semapps/jena-fuseki-webacl
    container_name: fuseki
    volumes:
      - ./data/fuseki:/fuseki:z
    ports:
      - '3030:3030'
    expose:
      - '3030'
    environment:
      ADMIN_PASSWORD: 'admin'

  mailcatcher:
    image: dockage/mailcatcher
    container_name: mailcatcher
    ports:
      - '1080:1080'
      - '1025:1025'
    restart: on-failure

  redis:
    image: redis
    container_name: redis
    expose:
      - '6379'
    ports:
      - '6379:6379'
    volumes:
      - ./data/redis:/data:z
    command: [ 'redis-server', '--appendonly', 'yes' ]

  arena:
    image: activitypods/arena
    container_name: arena
    restart: always
    volumes:
      - ./docker/arena.json:/opt/arena/src/server/config/index.json:z
    depends_on:
      - redis
    ports:
      - '4567:4567'
    expose:
      - '4567'
    environment:
      REDIS_HOST: 'redis'

  tripleadmin:
    image: mguihal/tripleadmin
    container_name: tripleadmin
    depends_on:
      - fuseki
    ports:
      - '3033:3033'
    extra_hosts:
      - 'localhost:host-gateway'
    environment:
      - TRIPLEADMIN_HOST=http://localhost:3030/
      - TRIPLEADMIN_USERNAME=admin

volumes:
  shapes:
    driver: local
    driver_opts:
      type: none
      device: './data/shapes'
      o: bind
  letsencrypt:
    driver: local
    driver_opts:
      type: none
      device: './data/letsencrypt'
      o: bind
