import urlJoin from 'url-join';
import { MigrationService } from '@semapps/migration';
import { arrayOf, getId, getDatasetFromUri, getParentContainerUri } from '@semapps/ldp';
import { MIME_TYPES } from '@semapps/mime-types';
import * as CONFIG from '../../config/config.ts';
import { ServiceSchema } from 'moleculer';
const MIGRATION_VERSION = '2.3.0';

const isLocal = (uri: string) => urlJoin(uri, '/').startsWith(urlJoin(CONFIG.BASE_URL as string, '/'));

// The 2.2 model doesn't set delegationAllowed to false, but authorizations created by a previous run may have it
const sameDelegation = (authorization: any, delegationAllowed: boolean) =>
  !!authorization['interop:delegationAllowed'] === delegationAllowed &&
  (authorization['interop:delegationLimit'] || undefined) === (delegationAllowed ? 1 : undefined);

/**
 * Migrate Pods to the ActivityPods 2.3 sharing model (social agent registrations and access authorizations).
 *
 * For each Pod, the resources shared in the 2.2 model (the profile with the contacts, the resources in an
 * apods:announces collection) are grouped by grantee, data registration and delegation right, so that each
 * group gets a single access authorization (and so a single access grant). Adding the resources one by one
 * would regenerate the grant each time (grants are immutable) and send a Create activity for each version.
 *
 * Local grantees are not notified: the reciprocal social agent registration is created directly in their Pod.
 * Grantees on other servers receive the usual Create activities. The delegated grants of the applications are
 * generated by repair.upgradeAllApps, to run after the migration.
 *
 * Can be run several times: Pods already on 2.3.0 are skipped, the authorizations that already exist are kept
 * (or completed), and a Pod for which an authorization could not be generated stays on its version.
 * Call it from the Moleculer CLI: call migration-2-3-0.migrate --username "*"
 */
const Migration230Schema = {
  name: 'migration-2-3-0' as const,
  // @ts-expect-error TS(2322): Type '{ name: "migration"; settings: { baseUrl: un... Remove this comment to see the full error message
  mixins: [MigrationService],
  settings: {
    baseUrl: CONFIG.BASE_URL
  },
  actions: {
    migrate: {
      async handler(ctx) {
        const { username } = ctx.params;
        const accounts = (await ctx.call('auth.account.find', {
          query: username === '*' ? undefined : { username }
        })) as any[];

        let migrated = 0;
        const failed: string[] = [];

        // Create the missing containers of ALL local Pods first, including the ones that are not migrated by this call:
        // the reciprocal social agent registrations are created in the Pods of the local contacts
        const allAccounts = (username === '*' ? accounts : await ctx.call('auth.account.find')) as any[];
        for (const account of allAccounts) {
          if (account.deletedAt) continue;
          try {
            await ctx.call('repair.createMissingContainers', { username: account.username });
          } catch (e: any) {
            this.logger.warn(`Unable to create the missing containers of ${account.webId}. Error: ${e.message}`);
          }
        }

        for (const { webId, username, version, deletedAt, ...rest } of accounts) {
          if (deletedAt) continue;
          if (version === MIGRATION_VERSION) {
            this.logger.info(`Pod of ${webId} is already on v${MIGRATION_VERSION}, skipping...`);
            continue;
          }

          this.logger.info(`Migrating Pod of ${webId} to v${MIGRATION_VERSION}...`);
          const start = Date.now();

          try {
            const errors = await this.actions.generateAuthorizations(
              { webId },
              { parentCtx: ctx, meta: { dataset: username, webId, skipObjectsWatcher: true } }
            );

            // Keep the Pod on its current version, so that the migration can be run again for it
            if (errors > 0) throw new Error(`${errors} authorization(s) could not be generated, see warnings above`);

            // Delete old containers (they may already be gone if the migration was interrupted)
            for (const path of ['data/interop/data-grant', 'data/interop/delegated-data-grant']) {
              const containerUri = urlJoin(webId, path);
              const containerExist = await ctx.call('ldp.container.exist', { containerUri, webId: 'system' });
              if (containerExist) {
                await ctx.call('ldp.container.delete', { containerUri, webId: 'system' });
              }
            }

            await ctx.call('auth.account.update', {
              id: rest['@id'],
              webId,
              username,
              version: MIGRATION_VERSION,
              ...rest
            });

            migrated++;
            this.logger.info(`Pod of ${webId} migrated in ${Math.round((Date.now() - start) / 1000)}s`);
          } catch (e: any) {
            failed.push(username);
            this.logger.error(`Unable to migrate Pod of ${webId} to ${MIGRATION_VERSION}. Error: ${e.message}`);
            console.error(e);
          }
        }

        // Also done for the Pods already migrated, whose local contacts may not have received the registrations
        // (with the first version of this migration, the Create activities failed for contacts not migrated yet)
        for (const { webId, username, deletedAt } of accounts) {
          if (deletedAt) continue;
          await this.actions.createReciprocalRegistrations(
            { webId },
            { parentCtx: ctx, meta: { dataset: username, webId, skipObjectsWatcher: true } }
          );
        }

        this.logger.info(
          `Migration to v${MIGRATION_VERSION} finished: ${migrated} Pod(s) migrated, ${failed.length} failed${
            failed.length > 0 ? ` (${failed.join(', ')})` : ''
          }`
        );

        return { migrated, failed };
      }
    },

    getSharedResources: {
      // Resources shared in the 2.2 model: the profile with the contacts, and the resources with an announces collection
      async handler(ctx) {
        const { webId } = ctx.params;
        const shares: { resourceUri: string; grantee: string; delegationAllowed: boolean }[] = [];

        const webIdData = await ctx.call('webid.get', { resourceUri: webId });
        if (webIdData.url && webIdData['apods:contacts']) {
          const contacts = await ctx.call('activitypub.collection.get', {
            resourceUri: webIdData['apods:contacts'],
            webId: 'system'
          });
          for (const contactUri of arrayOf(contacts?.items)) {
            shares.push({ resourceUri: webIdData.url, grantee: contactUri, delegationAllowed: false });
          }
        }

        const results = await ctx.call('triplestore.query', {
          query: `
            PREFIX apods: <http://activitypods.org/ns/core#>
            SELECT ?resourceUri ?announcesCollectionUri ?announcersCollectionUri
            WHERE {
              ?resourceUri apods:announces ?announcesCollectionUri .
              FILTER STRSTARTS(STR(?resourceUri), "${webId}/") .
              OPTIONAL { ?resourceUri apods:announcers ?announcersCollectionUri . }
            }
          `,
          webId: 'system'
        });

        for (const node of results as any[]) {
          const resourceUri = node.resourceUri.value;
          const announces = await ctx.call('activitypub.collection.get', {
            resourceUri: node.announcesCollectionUri.value,
            webId: 'system'
          });
          // Only resources whose sharing was delegated to someone have an announcers collection
          const announcers = node.announcersCollectionUri
            ? arrayOf(
                (
                  await ctx.call('activitypub.collection.get', {
                    resourceUri: node.announcersCollectionUri.value,
                    webId: 'system'
                  })
                )?.items
              )
            : [];
          for (const actorUri of arrayOf(announces?.items)) {
            shares.push({ resourceUri, grantee: actorUri, delegationAllowed: announcers.includes(actorUri) });
          }
        }

        return shares;
      }
    },

    generateAuthorizations: {
      // Generate one access authorization per grantee, data registration and delegation right
      async handler(ctx) {
        const { webId } = ctx.params;
        const shares = await this.actions.getSharedResources({ webId }, { parentCtx: ctx });

        // Resources of the same container share the same data registration
        const dataRegistrations = new Map<string, any>();
        const groups = new Map<string, any>();
        let errors = 0;

        for (const { resourceUri, grantee, delegationAllowed } of shares) {
          if (grantee === webId) continue;
          try {
            const containerUri = getParentContainerUri(resourceUri);
            if (!dataRegistrations.has(containerUri)) {
              dataRegistrations.set(
                containerUri,
                await ctx.call('data-registrations.getByResourceUri', { resourceUri, webId })
              );
            }
            const dataRegistration = dataRegistrations.get(containerUri);
            const key = `${grantee} ${getId(dataRegistration)} ${delegationAllowed}`;
            if (!groups.has(key))
              groups.set(key, { grantee, dataRegistration, delegationAllowed, resources: new Set() });
            groups.get(key).resources.add(resourceUri);
          } catch (e: any) {
            // E.g. a deleted resource or an unregistered container: there is nothing to authorize
            if (e.code !== 404) errors++;
            this.logger.warn(`Unable to find the data registration of ${resourceUri}. Error: ${e.message}`);
          }
        }

        this.logger.info(`${webId}: ${shares.length} shared resource(s), ${groups.size} authorization(s)`);

        for (const { grantee, dataRegistration, delegationAllowed, resources } of groups.values()) {
          try {
            await this.actions.createOrCompleteAuthorization(
              { webId, grantee, dataRegistration, delegationAllowed, resources: [...resources] },
              // Local grantees are not notified, their side is handled by createReciprocalRegistrations
              { parentCtx: ctx, meta: { skipNotifications: isLocal(grantee) } }
            );
          } catch (e: any) {
            errors++;
            this.logger.warn(`Unable to generate an authorization of ${webId} for ${grantee}. Error: ${e.message}`);
          }
        }

        return errors;
      }
    },

    createOrCompleteAuthorization: {
      async handler(ctx) {
        const { webId, grantee, dataRegistration, delegationAllowed, resources } = ctx.params;

        const container = await ctx.call('access-authorizations.list', {
          filters: {
            'http://www.w3.org/ns/solid/interop#dataOwner': webId,
            'http://www.w3.org/ns/solid/interop#grantee': grantee,
            'http://www.w3.org/ns/solid/interop#hasDataRegistration': getId(dataRegistration),
            'http://www.w3.org/ns/solid/interop#scopeOfAuthorization':
              'http://www.w3.org/ns/solid/interop#SelectedFromRegistry'
          },
          webId
        });

        const existing = arrayOf(container['ldp:contains']).find(
          (authorization: any) =>
            arrayOf(authorization['interop:accessMode']).join() === 'acl:Read' &&
            sameDelegation(authorization, delegationAllowed)
        );

        if (!existing) {
          await ctx.call('access-authorizations.post', {
            resource: {
              type: 'interop:AccessAuthorization',
              'interop:dataOwner': webId,
              'interop:grantedBy': webId,
              'interop:grantee': grantee,
              'interop:granteeType': 'interop:SocialAgent',
              'interop:registeredShapeTree': dataRegistration['interop:registeredShapeTree'],
              'interop:hasDataRegistration': getId(dataRegistration),
              'interop:hasDataInstance': resources,
              'interop:accessMode': ['acl:Read'],
              'interop:scopeOfAuthorization': 'interop:SelectedFromRegistry',
              'interop:delegationAllowed': delegationAllowed || undefined,
              'interop:delegationLimit': delegationAllowed ? 1 : undefined
            },
            contentType: MIME_TYPES.JSON,
            webId
          });
          return;
        }

        // Created by an interrupted run: complete it once with the missing resources (this replaces the grant)
        const existingResources = arrayOf(existing['interop:hasDataInstance']);
        const missingResources = resources.filter((uri: string) => !existingResources.includes(uri));
        if (missingResources.length > 0) {
          await ctx.call('access-authorizations.put', {
            resource: { ...existing, 'interop:hasDataInstance': [...existingResources, ...missingResources] },
            contentType: MIME_TYPES.JSON,
            webId
          });
        }
      }
    },

    createReciprocalRegistrations: {
      // For each local agent registered by this Pod, create (or link) the agent's registration of this Pod
      async handler(ctx) {
        const { webId } = ctx.params;

        const container = await ctx.call('social-agent-registrations.list', { webId });

        for (const registration of arrayOf(container['ldp:contains'])) {
          const agentUri = registration['interop:registeredAgent'];
          if (registration['interop:registeredBy'] !== webId || !agentUri || !isLocal(agentUri)) continue;
          if (registration['interop:reciprocalRegistration']) continue;

          try {
            const account = await ctx.call('auth.account.findByWebId', { webId: agentUri });
            if (!account || account.deletedAt) continue;

            // Created or updated in the Pod of the agent
            const agentMeta = { dataset: getDatasetFromUri(agentUri), webId: agentUri, skipNotifications: true };
            const reciprocalRegistrationUri = await ctx.call(
              'social-agent-registrations.createOrUpdate',
              { agentUri: webId, podOwner: agentUri, reciprocalRegistrationUri: getId(registration) },
              { meta: agentMeta }
            );

            // Moleculer copies the meta of a child call back to its parent, so the dataset must be set again
            await ctx.call(
              'social-agent-registrations.createOrUpdate',
              { agentUri, podOwner: webId, reciprocalRegistrationUri },
              { meta: { dataset: getDatasetFromUri(webId), webId, skipNotifications: true } }
            );
          } catch (e: any) {
            this.logger.warn(
              `Unable to create the reciprocal registration of ${webId} in the Pod of ${agentUri}. Error: ${e.message}`
            );
          }
        }
      }
    }
  }
} satisfies ServiceSchema;

export default Migration230Schema;

declare global {
  export namespace Moleculer {
    export interface AllServices {
      [Migration230Schema.name]: typeof Migration230Schema;
    }
  }
}
